#pragma once

// Browser page kept in a header so the Arduino sketch preprocessor never
// mistakes embedded JavaScript functions for C++ declarations.

const char INDEX_HTML[] PROGMEM = R"HTML(
<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1">
<title>CUBE.FX / 5×5×5</title><style>
:root{--ink:#050706;--panel:#0c110e;--line:#c8ff20;--acid:#8cff00;--muted:#789077;--red:#ff4e40}
*{box-sizing:border-box}body{margin:0;background:var(--ink);color:#eaffd2;font-family:ui-monospace,Menlo,monospace;min-height:100vh}
header{border-bottom:3px solid var(--line);padding:16px 20px;display:flex;justify-content:space-between;gap:12px;background:#0b100d}h1{margin:0;font-size:clamp(22px,4vw,40px);letter-spacing:-2px}small{color:var(--muted)}
#shell{display:grid;grid-template-columns:150px 1fr;min-height:calc(100vh - 78px)}nav{border-right:3px solid var(--line);padding:12px;background:#081009}nav button{width:100%;text-align:left;margin:0 0 8px;padding:10px;border:2px solid #426840;background:#101b12;color:#d9ffd1;font:inherit;cursor:pointer}nav button:hover,nav button.active{background:var(--acid);color:#061000;border-color:var(--acid)}main{padding:20px;max-width:1000px}.panel{display:none}.panel.active{display:block}.grid{display:grid;grid-template-columns:minmax(270px,1fr) minmax(270px,1fr);gap:16px}.box{border:2px solid #426840;background:var(--panel);padding:16px}.box h2{margin:0 0 12px;color:var(--line);font-size:16px}.status{font-size:20px;color:var(--acid);padding:8px 0}
select,input,button{font:inherit}select,input[type=text]{width:100%;padding:12px;background:#030603;color:var(--acid);border:2px solid var(--line)}input[type=range]{width:100%;accent-color:var(--acid)}.row{display:flex;justify-content:space-between;gap:12px;align-items:center;padding:8px 0;border-bottom:1px solid #29412a}.row:last-child{border:0}.control{display:block;margin:14px 0}.control label{display:flex;justify-content:space-between;color:#c4ddbd;margin-bottom:6px}.action{padding:11px 13px;border:2px solid var(--line);background:var(--acid);color:#061000;font-weight:800;cursor:pointer}.action.dark{background:#0d170e;color:var(--line)}.action.red{border-color:var(--red);color:#ffd8d0;background:#28100d}.actions{display:flex;gap:8px;flex-wrap:wrap}canvas{width:100%;background:#020403;border:2px solid #426840;image-rendering:pixelated}.note{color:var(--muted);font-size:12px;line-height:1.5}.credit{border-left:3px solid var(--red);padding-left:10px;color:#ffd5cb;font-size:12px;line-height:1.4}
@media(max-width:680px){#shell{grid-template-columns:1fr}nav{border-right:0;border-bottom:3px solid var(--line);display:flex;overflow:auto;padding:8px}nav button{width:auto;white-space:nowrap;margin:0 6px 0 0}.grid{grid-template-columns:1fr}main{padding:12px}}
</style></head><body><header><div><h1>CUBE.FX</h1><small>5×5×5 / 125 VOXELS / ESP32-C3</small></div><div id="net">CONNECTING…</div></header>
<div id="shell"><nav><button class="active" data-tab="live">01 LIVE</button><button data-tab="patterns">02 PATTERNS</button><button data-tab="control">03 CONTROL</button><button data-tab="about">04 ABOUT</button></nav><main>
<section class="panel active" id="live"><div class="grid"><div class="box"><h2>NOW PLAYING</h2><div class="status" id="name">—</div><div class="row"><span>MODE</span><b id="mode">—</b></div><div class="row"><span>BRIGHTNESS</span><b id="brightRead">—</b></div><div class="row"><span>SPEED</span><b id="speedRead">—</b></div><div class="row"><span>FRAME CAP</span><b id="fpsRead">—</b></div><p class="note">The preview is a logical voxel view: red is the bottom–rear–left origin. It updates from the live cube framebuffer.</p><div class="actions"><button class="action" onclick="next()">NEXT</button><button class="action dark" onclick="toggleAuto()" id="autoBtn">AUTO</button></div></div><div class="box"><h2>LIVE VOXEL PREVIEW</h2><canvas id="cube" width="500" height="420"></canvas></div></div></section>
<section class="panel" id="patterns"><div class="box"><h2>PATTERN GALLERY</h2><select id="pattern" size="37"></select><p class="note">Select an effect to enter manual mode immediately. Long-press GPIO4 to show Banner mode; long-press GPIO8 to select the next pattern. Short presses control the active effect, including left/right movement in Single-player Pong.</p></div></section>
<section class="panel" id="control"><div class="box"><h2>ENGINE CONTROL</h2><div class="control"><label>BRIGHTNESS <b id="bv">100</b></label><input id="brightness" type="range" min="1" max="255" value="100"></div><div class="control"><label>MOTION SPEED <b id="sv">150</b></label><input id="speed" type="range" min="1" max="255" value="150"></div><div class="control"><label>FRAME RATE CAP <b id="fv">120</b> FPS</label><input id="fps" type="range" min="30" max="120" value="120"></div><div class="control"><label>AUTO DWELL, SECONDS <b id="cv">30</b></label><input id="cycle" type="range" min="5" max="120" value="30"></div><div class="actions"><button class="action" onclick="applyControls()">APPLY</button><button class="action red" onclick="api('reseed=1')">RESEED LIFE</button></div></div><div class="box" style="margin-top:16px"><h2>3×5 PERIMETER BANNER</h2><div class="control"><label>MESSAGE</label><input id="bannerText" type="text" maxlength="60" value="CUBE 4 3 2 1 0"></div><div class="control"><label>FONT MODE</label><select id="bannerFont"><option value="3">3×5 / COMPACT</option><option value="5">5×5 / BOLD FULL-FACE</option></select></div><div class="control"><label>COLOUR <b id="bhv">96</b></label><input id="bannerHue" type="range" min="0" max="255" value="96"></div><div class="control"><label>SCROLL SPEED <b id="bsv">150</b></label><input id="bannerSpeed" type="range" min="1" max="255" value="150"></div><div class="actions"><button class="action" onclick="applyBanner()">SEND TO CUBE</button><button class="action dark" onclick="api('pattern=11')">SHOW BANNER</button></div><p class="note">Choose compact 3×5 or bold 5×5 full-face letters. The message wraps around the rear, right, front, and left exterior faces with corrected forward travel. Supported: A–Z, 0–9, space, period, dash, colon, exclamation, and question mark.</p></div></section>
<section class="panel" id="about"><div class="box"><h2>WHAT IS CUBE.FX?</h2><p>A cube-first browser controller inspired by the convenience of <a href="https://github.com/kitesurfer1404/WS2812FX" style="color:#c8ff20">WS2812FX</a>, but built for 3-D voxel patterns rather than flat LED strips.</p><p class="credit">FEED ME , I'M POOR AND I MADE THIS FOR FREE — https://paypal.me/Mystereon</p><p class="note">Created by Dad (MysterEon) &amp; Manus. GPIO4 short press performs the primary pattern action and long press enters Banner mode. GPIO8 short press performs the secondary pattern action and long press advances to the next pattern. Release GPIO8 while resetting because it is a C3 strapping pin.</p></div></section>
</main></div><script>
const names=['Red Vector Cube','3-D Matrix Rain','Neon Plasma','Volume Fire','Twin Spirals','Wrapping Comets','Single-player Pong','Conway 3-D Life','Cloud Volume','White Glitter','Corner Cubes','3x5 Perimeter Banner','Bullet Wall','Padded Cell','Block Run','Parallax Starfield','Trench Run','Running Legs','Fairies in Green Box','Orange Fish Tank','Three-Layer Pyramid','Matrix Drift','Intense Fire','Magical Blue Fire','Explosions','Launching Fireworks','Pixel Pasture','Red Matrix Rain','Voxel Minesweeper','Big Moon & Stars','Nixie Tube','Black Hole Vortex','Stargate Dial-Up','3-D Defender','3-D Chequerboard','Hellraiser Puzzle Cube','3-D Rubik\'s Cube'];
let state={}, frame=[];let engineControlsDirty=false,bannerControlsDirty=false;const engineControls=['brightness','speed','cycle','fps'];const $=id=>document.getElementById(id);const ctx=$('cube').getContext('2d');
names.forEach((n,i)=>{let o=document.createElement('option');o.value=i;o.textContent=String(i+1).padStart(2,'0')+' / '+n;$('pattern').append(o)});
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')});
$('pattern').onchange=()=>api('pattern='+$('pattern').value);engineControls.forEach(k=>$(k).oninput=()=>{engineControlsDirty=true;$(k[0]+'v').textContent=$(k).value});['bannerText','bannerFont','bannerHue','bannerSpeed'].forEach(k=>$(k).oninput=()=>{bannerControlsDirty=true});$('bannerHue').oninput=()=>{bannerControlsDirty=true;$('bhv').textContent=$('bannerHue').value};$('bannerSpeed').oninput=()=>{bannerControlsDirty=true;$('bsv').textContent=$('bannerSpeed').value};$('bannerFont').onchange=()=>{bannerControlsDirty=true};
function api(q){return fetch('/api/control?'+q).then(()=>refresh())}function next(){api('next=1')}function toggleAuto(){api('auto='+(state.auto?0:1))}function applyControls(){return api('brightness='+$('brightness').value+'&speed='+$('speed').value+'&fps='+$('fps').value+'&cycle='+$('cycle').value).then(()=>{engineControlsDirty=false;render()})}function applyBanner(){return api('text='+encodeURIComponent($('bannerText').value)+'&bannerFont='+$('bannerFont').value+'&bannerHue='+$('bannerHue').value+'&bannerSpeed='+$('bannerSpeed').value).then(()=>{bannerControlsDirty=false;render()})}
function draw(){const w=500,h=420;ctx.fillStyle='#020403';ctx.fillRect(0,0,w,h);const p=(x,y,z)=>[250+(x-y)*34,335-(x+y)*17-z*47];for(let z=0;z<5;z++)for(let y=0;y<5;y++)for(let x=0;x<5;x++){let [px,py]=p(x,y,z),col=frame[z*25+y*5+x]||'#000000';ctx.beginPath();ctx.fillStyle=col;ctx.arc(px,py,9,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#1c301d';ctx.stroke()}}
function render(){if(!state.name)return;$('name').textContent=state.name;$('mode').textContent=state.auto?'AUTO':'MANUAL';$('brightRead').textContent=state.brightness;$('speedRead').textContent=state.speed;$('fpsRead').textContent=state.fps+' FPS';$('net').textContent=(state.ap?'AP @ ':'WIFI @ ')+state.ip;$('autoBtn').textContent=state.auto?'PAUSE AUTO':'RESUME AUTO';$('pattern').value=state.pattern;if(!engineControlsDirty){$('brightness').value=state.brightness;$('speed').value=state.speed;$('fps').value=state.fps;$('cycle').value=state.cycle;engineControls.forEach(k=>$(k[0]+'v').textContent=$(k).value)}if(!bannerControlsDirty){$('bannerHue').value=state.bannerHue;$('bannerSpeed').value=state.bannerSpeed;$('bannerFont').value=state.bannerFont;if(document.activeElement!==$('bannerText'))$('bannerText').value=state.banner;$('bhv').textContent=state.bannerHue;$('bsv').textContent=state.bannerSpeed}draw()}
function refresh(){return Promise.all([fetch('/api/state').then(r=>r.json()),fetch('/api/frame').then(r=>r.json())]).then(a=>{state=a[0];frame=a[1].voxels;render()}).catch(()=>{$('net').textContent='RECONNECTING…'})}setInterval(refresh,650);refresh();
</script></body></html>
)HTML";
