#pragma once

// Browser page remains in a header so Arduino's preprocessor does not interpret
// JavaScript functions as sketch declarations.
const char INDEX_HTML[] PROGMEM = R"HTML(
<!doctype html>
<html><head><meta name="viewport" content="width=device-width,initial-scale=1">
<title>CUBE.FX / 5×5×5</title>
<style>
:root{--ink:#050706;--panel:#0c110e;--line:#c8ff20;--acid:#8cff00;--muted:#789077;--red:#ff4e40;--cyan:#77e8ff}
*{box-sizing:border-box}body{margin:0;background:var(--ink);color:#eaffd2;font-family:ui-monospace,Menlo,monospace;min-height:100vh}header{border-bottom:3px solid var(--line);padding:16px 20px;display:flex;justify-content:space-between;gap:12px;background:#0b100d}h1{margin:0;font-size:clamp(22px,4vw,40px);letter-spacing:-2px}small{color:var(--muted)}
#shell{display:grid;grid-template-columns:150px 1fr;min-height:calc(100vh - 78px)}nav{border-right:3px solid var(--line);padding:12px;background:#081009}nav button{width:100%;text-align:left;margin:0 0 8px;padding:10px;border:2px solid #426840;background:#101b12;color:#d9ffd1;font:inherit;cursor:pointer}nav button:hover,nav button.active{background:var(--acid);color:#061000;border-color:var(--acid)}main{padding:20px;max-width:1160px}.panel{display:none}.panel.active{display:block}.grid{display:grid;grid-template-columns:minmax(270px,1fr) minmax(270px,1fr);gap:16px}.box{border:2px solid #426840;background:var(--panel);padding:16px;margin-bottom:16px}.box h2{margin:0 0 12px;color:var(--line);font-size:16px}.status{font-size:20px;color:var(--acid);padding:8px 0}
select,input,button{font:inherit}select,input[type=text],input[type=number],input[type=color]{width:100%;padding:10px;background:#030603;color:var(--acid);border:2px solid var(--line)}input[type=color]{height:48px;padding:3px}input[type=range]{width:100%;accent-color:var(--acid)}.row{display:flex;justify-content:space-between;gap:12px;align-items:center;padding:8px 0;border-bottom:1px solid #29412a}.row:last-child{border:0}.control{display:block;margin:14px 0}.control label{display:flex;justify-content:space-between;color:#c4ddbd;margin-bottom:6px}.action{padding:11px 13px;border:2px solid var(--line);background:var(--acid);color:#061000;font-weight:800;cursor:pointer}.action.dark{background:#0d170e;color:var(--line)}.action.red{border-color:var(--red);color:#ffd8d0;background:#28100d}.action.cyan{border-color:var(--cyan);background:#082329;color:var(--cyan)}.actions,.slot-row,.step-row{display:flex;gap:8px;flex-wrap:wrap}.note{color:var(--muted);font-size:12px;line-height:1.5}.credit{border-left:3px solid var(--red);padding-left:10px;color:#ffd5cb;font-size:12px;line-height:1.4}canvas{width:100%;background:#020403;border:2px solid #426840;image-rendering:pixelated}
.slot,.step{min-width:42px;padding:9px 7px;background:#101b12;border:2px solid #426840;color:#d9ffd1;font:inherit;cursor:pointer}.slot.active,.step.active{background:var(--acid);color:#061000;border-color:var(--acid)}.step{min-width:34px;font-size:11px}.editor-controls{display:grid;grid-template-columns:1fr 1fr;gap:12px;align-items:end}.layer-deck{display:grid;grid-template-columns:repeat(5,minmax(135px,1fr));gap:10px;overflow:auto;padding-bottom:6px}.layer{border:1px solid #426840;background:#071008;padding:8px;min-width:135px}.layer h3{margin:0 0 7px;font-size:12px;color:var(--cyan)}.voxel-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:3px}.voxel{aspect-ratio:1;border:1px solid #426840;background:#020403;cursor:pointer;padding:0;min-width:18px}.voxel.on{border-color:#fff;box-shadow:0 0 8px currentColor}.editor-status{color:var(--cyan);font-size:12px;min-height:18px;margin:8px 0}
@media(max-width:680px){#shell{grid-template-columns:1fr}nav{border-right:0;border-bottom:3px solid var(--line);display:flex;overflow:auto;padding:8px}nav button{width:auto;white-space:nowrap;margin:0 6px 0 0}.grid,.editor-controls{grid-template-columns:1fr}main{padding:12px}.layer-deck{grid-template-columns:repeat(5,130px)}}
</style></head><body>
<header><div><h1>CUBE.FX</h1><small>5×5×5 / 125 VOXELS + 12-PIXEL RING / ESP32-S3</small></div><div><div id="net">CONNECTING…</div><small id="command">READY</small></div></header>
<div id="shell"><nav><button class="active" data-tab="live">01 LIVE</button><button data-tab="patterns">02 PATTERNS</button><button data-tab="control">03 CONTROL</button><button data-tab="about">04 ABOUT</button><button data-tab="editor">05 SEQUENCER</button></nav><main>
<section class="panel active" id="live"><div class="grid"><div class="box"><h2>NOW PLAYING</h2><div class="status" id="name">—</div><div class="row"><span>MODE</span><b id="mode">—</b></div><div class="row"><span>BRIGHTNESS</span><b id="brightRead">—</b></div><div class="row"><span>SPEED</span><b id="speedRead">—</b></div><div class="row"><span>FRAME CAP</span><b id="fpsRead">—</b></div><p class="note">The preview is a logical voxel view: red is the bottom–rear–left origin. It updates from the live cube framebuffer.</p><div class="actions"><button class="action" onclick="next()">NEXT</button><button class="action dark" onclick="toggleAuto()" id="autoBtn">AUTO</button></div></div><div class="box"><h2>LIVE VOXEL PREVIEW</h2><canvas id="cube" width="500" height="420"></canvas></div></div></section>
<section class="panel" id="patterns"><div class="box"><h2>PATTERN GALLERY</h2><select id="pattern" size="62"></select><div class="actions" style="margin-top:12px"><button class="action" onclick="selectPattern()">PLAY SELECTED PATTERN</button></div><p class="note">Selecting enters manual mode; PLAY is the deliberate replay route. User Patterns 01–05 are saved sixteen-step sequences made in the sequencer tab. While a User Pattern is running, short GPIO2 restarts at step 01 and short GPIO4 advances one step. Global long-press Banner / Next behaviour is unchanged.</p></div></section>
<section class="panel" id="control"><div class="box"><h2>ENGINE CONTROL</h2><div class="control"><label>BRIGHTNESS <b id="bv">100</b></label><input id="brightness" type="range" min="1" max="255" value="100"></div><div class="control"><label>MOTION SPEED <b id="sv">150</b></label><input id="speed" type="range" min="1" max="255" value="150"></div><div class="control"><label>FRAME RATE CAP <b id="fv">120</b> FPS</label><input id="fps" type="range" min="30" max="120" value="120"></div><div class="control"><label>AUTO DWELL, SECONDS <b id="cv">30</b></label><input id="cycle" type="range" min="5" max="120" value="30"></div><div class="actions"><button class="action" onclick="applyControls()">APPLY</button><button class="action red" onclick="api('reseed=1','LIFE RESEEDED')">RESEED LIFE</button></div></div><div class="box"><h2>3×5 PERIMETER BANNER</h2><div class="control"><label>MESSAGE</label><input id="bannerText" type="text" maxlength="60" value="CUBE 4 3 2 1 0"></div><div class="control"><label>FONT MODE</label><select id="bannerFont"><option value="3">3×5 / COMPACT</option><option value="5">5×5 / BOLD FULL-FACE</option></select></div><div class="control"><label>COLOUR <b id="bhv">96</b></label><input id="bannerHue" type="range" min="0" max="255" value="96"></div><div class="control"><label>SCROLL SPEED <b id="bsv">150</b></label><input id="bannerSpeed" type="range" min="1" max="255" value="150"></div><div class="actions"><button class="action" onclick="applyBanner()">SEND TO CUBE</button><button class="action dark" onclick="api('pattern=11','BANNER PLAYING')">SHOW BANNER</button></div></div><div class="box"><h2>EASTER EGG CONTROL DECK</h2><p class="note">Direct owner controls: each command plays its matching five-second hidden scene. Physical activation routes remain secret and still work.</p><div class="actions"><button class="action red" onclick="triggerSecret(0,'RED EYE')">01 RED EYE</button><button class="action" onclick="triggerSecret(1,'WARM PULSE')">02 WARM PULSE</button><button class="action dark" onclick="triggerSecret(2,'POCKET CLOCK')">03 POCKET CLOCK</button><button class="action" onclick="triggerSecret(3,'COUNTDOWN')">04 COUNTDOWN</button><button class="action red" onclick="triggerSecret(4,'EXPLOSION BURST')">05 EXPLOSION BURST</button></div></div></section>
<section class="panel" id="about"><div class="box"><h2>WHAT IS CUBE.FX?</h2><p>A cube-first browser controller inspired by the convenience of <a href="https://github.com/kitesurfer1404/WS2812FX" style="color:#c8ff20">WS2812FX</a>, but built for 3-D voxel patterns rather than flat LED strips.</p><p class="credit">FEED ME , I'M POOR AND I MADE THIS FOR FREE — https://paypal.me/Mystereon</p><p class="note">Created by Dad (MysterEon) &amp; Manus. Five user sequencer slots are CubeFX-owned and separate from the pure official FastLED source collection and future CubeFX interpretations.</p></div></section>
<section class="panel" id="editor"><div class="box"><h2>FIVE-SLOT / 16-STEP USER SEQUENCER</h2><p class="note">Choose a slot, draw one step at a time through five physical layers, then deliberately send the staged slot to the cube. Every enabled voxel in a step shares its selected colour; change colour across steps for multicolour animation.</p><div class="row"><span>USER SLOT</span><b id="slotRead">01</b></div><div id="slotRow" class="slot-row"></div><div class="row"><span>SEQUENCE STEP</span><b id="stepRead">01 / 16</b></div><div id="stepRow" class="step-row"></div><div class="editor-controls"><div class="control"><label>STEP COLOUR</label><input id="userColour" type="color" value="#00B4FF"></div><div class="control"><label>HOLD, MILLISECONDS</label><input id="userHold" type="number" min="40" max="5000" step="20" value="240"></div></div><div class="actions"><button class="action dark" onclick="clearUserStep()">CLEAR STEP</button><button class="action red" onclick="clearUserSlot()">CLEAR SLOT</button><button class="action cyan" onclick="loadUserSlot(userSlot)">LOAD FROM CUBE</button><button class="action" onclick="sendUserSlot()">SEND SLOT TO CUBE</button><button class="action" onclick="playUserSlot()">PLAY SLOT</button></div><div id="editorStatus" class="editor-status">STAGED LOCALLY — LOAD OR SEND A SLOT</div><div id="layerDeck" class="layer-deck"></div><p class="note">Panels run from top `z=4` to base `z=0`. A lit square is one physical voxel. SEND stages all 16 masks, then commits one 320-byte slot to NVS.</p></div></section>
</main></div>
<script>
const names=['Red Vector Cube','3-D Matrix Rain','Neon Plasma','Volume Fire','Twin Spirals','Wrapping Comets','Single-player Pong','Conway 3-D Life','Cloud Volume','White Glitter','Corner Cubes','3x5 Perimeter Banner','Bullet Wall','Padded Cell','Block Run','Parallax Starfield','Trench Run','Running Legs','Fairies in Green Box','Orange Fish Tank','Three-Layer Pyramid','Matrix Drift','Intense Fire','Magical Blue Fire','Explosions','Launching Fireworks','Pixel Pasture','Red Matrix Rain','Voxel Minesweeper','Big Moon & Stars','Nixie Tube','Black Hole Vortex','Stargate Dial-Up','3-D Defender','3-D Chequerboard','Hellraiser Puzzle Cube','3-D Rubik\'s Cube','Lissajous Layer Ripple','Zarch: Voxel Defender','Ring Bouncer','Help Me Obi-Wan Hologram','Voxel World Explorer','Phone VU Meter','Phone Spectrum 3-D','Cloud-Top Rain','Rotating Gold O','Reactor Core','Reactor Core Meltdown','Targeting System','Phosphor Green Radar','Ghost Detector','Alert','Intersecting Planes','Oscillating Wave Field','Rainbow Spiral','Plasma Entity Containment','Race Circuit','User Pattern 01','User Pattern 02','User Pattern 03','User Pattern 04','User Pattern 05'];
const fastledSources=['AnalogOutput','Animartrix','AnimartrixRing','Apa102','Apa102HD','Asio','Async','Audio','AudioFftParity','AudioInput','AudioReactive','AudioUrl','AutoResearch','BeatDetection','Blink','BlinkParallel','Blur','Blur2d','BlurBenchmark','Chromancer','Codec','ColorBoost','ColorPalette','ColorTemperature','Corkscrew','Cylon','DemoReel100','Downscale','EaseInOut','ElPanelReactive','Esp8266Uart','FestivalStick','Fire2012','Fire2012WithPalette','Fire2023','FireCylinder','FireMatrix','FirstLight','FlowField','Fx','HD107','HSVTest','Json','LuminescentGrand','Luminova','MoodRing','Multiple','Noise','NoisePlayground','NoisePlusPalette','OTA','Overclock','Pacifica','ParallelSPI','PerfDisc','PinMode','Pintest','Ports','Pride2015','RGBCalibrate','RGBSetDemo','RGBW','RGBWColorimetric','RGBWEmulated','RGBWW','RX','Remote','SIMD','Sailboat','SmartMatrix','SpecialDrivers','Spi','Test','TwinkleFox','UITest','WS2816','WasmScreenCoords','Wave','Wave2d','XYMatrix','XYPath','hydropack','wasm'];
names.push(...fastledSources.map(source=>'CubeFX Interpretation — '+source));
const $=id=>document.getElementById(id),engineControls=['brightness','speed','cycle','fps'],ctx=$('cube').getContext('2d');let state={},frame=[],engineControlsDirty=false,bannerControlsDirty=false;
names.forEach((name,index)=>{const option=document.createElement('option');option.value=index;option.textContent=String(index+1).padStart(2,'0')+' / '+name;$('pattern').append(option)});
document.querySelectorAll('nav button').forEach(button=>button.onclick=()=>{document.querySelectorAll('nav button,.panel').forEach(item=>item.classList.remove('active'));button.classList.add('active');$(button.dataset.tab).classList.add('active')});
$('pattern').onchange=()=>selectPattern();engineControls.forEach(key=>$(key).oninput=()=>{engineControlsDirty=true;$(key[0]+'v').textContent=$(key).value});['bannerText','bannerFont','bannerHue','bannerSpeed'].forEach(key=>$(key).oninput=()=>bannerControlsDirty=true);$('bannerHue').oninput=()=>{bannerControlsDirty=true;$('bhv').textContent=$('bannerHue').value};$('bannerSpeed').oninput=()=>{bannerControlsDirty=true;$('bsv').textContent=$('bannerSpeed').value};$('bannerFont').onchange=()=>bannerControlsDirty=true;
function setCommand(message){$('command').textContent=message}function api(query,label='COMMAND'){setCommand(label+'…');return fetch('/api/control?'+query,{cache:'no-store'}).then(response=>{if(!response.ok)throw Error('HTTP '+response.status);return response.json()}).then(nextState=>{state=nextState;render();setCommand(label+' ✓');return refresh()}).catch(error=>{setCommand(label+' FAILED');throw error})}function selectPattern(){const id=Number($('pattern').value);return api('pattern='+id,'PLAYING '+names[id])}function triggerSecret(scene,label){return api('secret='+scene,label+' TRIGGERED')}function next(){api('next=1','NEXT PATTERN')}function toggleAuto(){api('auto='+(state.auto?0:1),state.auto?'AUTO PAUSED':'AUTO RESUMED')}function applyControls(){return api('brightness='+$('brightness').value+'&speed='+$('speed').value+'&fps='+$('fps').value+'&cycle='+$('cycle').value,'ENGINE APPLIED').then(()=>{engineControlsDirty=false;render()})}function applyBanner(){return api('text='+encodeURIComponent($('bannerText').value)+'&bannerFont='+$('bannerFont').value+'&bannerHue='+$('bannerHue').value+'&bannerSpeed='+$('bannerSpeed').value,'BANNER SENT').then(()=>{bannerControlsDirty=false;render()})}
function draw(){ctx.fillStyle='#020403';ctx.fillRect(0,0,500,420);const pos=(x,y,z)=>[250+(x-y)*34,335-(x+y)*17-z*47];for(let z=0;z<5;z++)for(let y=0;y<5;y++)for(let x=0;x<5;x++){const p=pos(x,y,z),colour=frame[z*25+y*5+x]||'#000000';ctx.beginPath();ctx.fillStyle=colour;ctx.arc(p[0],p[1],9,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#1c301d';ctx.stroke()}}
function render(){if(!state.name)return;$('name').textContent=state.name;$('mode').textContent=state.auto?'AUTO':'MANUAL';$('brightRead').textContent=state.brightness;$('speedRead').textContent=state.speed;$('fpsRead').textContent=state.fps+' FPS';$('net').textContent=(state.ap?'AP @ ':'WIFI @ ')+state.ip;$('autoBtn').textContent=state.auto?'PAUSE AUTO':'RESUME AUTO';$('pattern').value=state.pattern;if(!engineControlsDirty){engineControls.forEach(key=>{$(key).value=state[key];$(key[0]+'v').textContent=$(key).value})}if(!bannerControlsDirty){$('bannerHue').value=state.bannerHue;$('bannerSpeed').value=state.bannerSpeed;$('bannerFont').value=state.bannerFont;if(document.activeElement!==$('bannerText'))$('bannerText').value=state.banner;$('bhv').textContent=state.bannerHue;$('bsv').textContent=state.bannerSpeed}draw()}
function refresh(){return Promise.all([fetch('/api/state').then(response=>response.json()),fetch('/api/frame').then(response=>response.json())]).then(result=>{state=result[0];frame=result[1].voxels;render()}).catch(()=>{$('net').textContent='RECONNECTING…'})}setInterval(refresh,650);refresh();
const USTEPS=16,USLOTS=5,UMASK=16;let userSlot=0,userStep=0,userSteps=Array.from({length:USTEPS},()=>blankUserStep());
function blankUserStep(){return{mask:new Uint8Array(UMASK),r:0,g:180,b:255,hold:12}}function bitOn(step,index){return(step.mask[index>>3]&(1<<(index&7)))!==0}function toggleBit(step,index){step.mask[index>>3]^=1<<(index&7)}function maskHex(mask){return Array.from(mask,value=>value.toString(16).padStart(2,'0')).join('').toUpperCase()}function fromHex(text){const mask=new Uint8Array(UMASK);for(let index=0;index<UMASK;index++)mask[index]=parseInt(text.slice(index*2,index*2+2),16)||0;mask[15]&=31;return mask}function hexColour(step){return '#'+[step.r,step.g,step.b].map(value=>value.toString(16).padStart(2,'0')).join('')}function currentUserStep(){return userSteps[userStep]}function setEditorStatus(text){$('editorStatus').textContent=text}
function syncUserInputs(){const step=currentUserStep(),colour=$('userColour').value;step.r=parseInt(colour.slice(1,3),16);step.g=parseInt(colour.slice(3,5),16);step.b=parseInt(colour.slice(5,7),16);step.hold=Math.max(2,Math.min(250,Math.round(Number($('userHold').value||240)/20)))}
function renderUserEditor(){const step=currentUserStep(),colour=hexColour(step);$('slotRead').textContent=String(userSlot+1).padStart(2,'0');$('stepRead').textContent=String(userStep+1).padStart(2,'0')+' / 16';$('userColour').value=colour;$('userHold').value=step.hold*20;$('slotRow').innerHTML=Array.from({length:USLOTS},(_,index)=>`<button class="slot ${index===userSlot?'active':''}" onclick="loadUserSlot(${index})">SLOT ${String(index+1).padStart(2,'0')}</button>`).join('');$('stepRow').innerHTML=Array.from({length:USTEPS},(_,index)=>`<button class="step ${index===userStep?'active':''}" onclick="chooseUserStep(${index})">${String(index+1).padStart(2,'0')}</button>`).join('');let deck='';for(let z=4;z>=0;z--){deck+=`<div class="layer"><h3>LAYER z=${z}</h3><div class="voxel-grid">`;for(let y=0;y<5;y++)for(let x=0;x<5;x++){const index=z*25+y*5+x,on=bitOn(step,index);deck+=`<button aria-label="x ${x} y ${y} z ${z}" class="voxel ${on?'on':''}" style="color:${colour};background:${on?colour:'#020403'}" onclick="toggleVoxel(${index})"></button>`}deck+='</div></div>'}$('layerDeck').innerHTML=deck}
function chooseUserStep(step){syncUserInputs();userStep=step;renderUserEditor()}function toggleVoxel(index){syncUserInputs();toggleBit(currentUserStep(),index);setEditorStatus('STEP '+String(userStep+1).padStart(2,'0')+' STAGED LOCALLY');renderUserEditor()}function clearUserStep(){userSteps[userStep]=blankUserStep();setEditorStatus('STEP '+String(userStep+1).padStart(2,'0')+' CLEARED LOCALLY');renderUserEditor()}function clearUserSlot(){userSteps=Array.from({length:USTEPS},()=>blankUserStep());userStep=0;setEditorStatus('SLOT '+String(userSlot+1).padStart(2,'0')+' CLEARED LOCALLY — SEND TO COMMIT');renderUserEditor()}
function editorFetch(query){return fetch('/api/control?'+query,{cache:'no-store'}).then(async response=>{const data=await response.json();if(!response.ok)throw Error(data.message||'HTTP '+response.status);return data})}function loadUserSlot(slot){syncUserInputs();setEditorStatus('LOADING SLOT '+String(slot+1).padStart(2,'0')+'…');editorFetch('userLoad='+slot).then(data=>{userSlot=slot;userStep=0;userSteps=data.steps.map(step=>({mask:fromHex(step.mask),r:step.r,g:step.g,b:step.b,hold:step.hold}));setEditorStatus('SLOT '+String(slot+1).padStart(2,'0')+' LOADED FROM CUBE ✓');renderUserEditor()}).catch(error=>setEditorStatus('LOAD FAILED — '+error.message))}
async function sendUserSlot(){syncUserInputs();setEditorStatus('SENDING 16 STEPS TO CUBE…');try{for(let index=0;index<USTEPS;index++){const step=userSteps[index],query='userStep=1&slot='+userSlot+'&step='+index+'&mask='+maskHex(step.mask)+'&r='+step.r+'&g='+step.g+'&b='+step.b+'&hold='+step.hold;await editorFetch(query)}await editorFetch('userSave='+userSlot);setEditorStatus('SLOT '+String(userSlot+1).padStart(2,'0')+' SAVED IN CUBE NVS ✓');setCommand('USER SLOT SAVED ✓')}catch(error){setEditorStatus('SEND FAILED — '+error.message);setCommand('USER SLOT SEND FAILED')}}function playUserSlot(){syncUserInputs();editorFetch('userPlay='+userSlot).then(data=>{state=data;render();setEditorStatus('PLAYING USER PATTERN '+String(userSlot+1).padStart(2,'0')+' ✓');setCommand('USER PATTERN PLAYING ✓')}).catch(error=>setEditorStatus('PLAY FAILED — '+error.message))}
$('userColour').oninput=()=>{syncUserInputs();renderUserEditor()};$('userHold').oninput=()=>{syncUserInputs();setEditorStatus('HOLD STAGED FOR STEP '+String(userStep+1).padStart(2,'0'))};renderUserEditor();
</script></body></html>
)HTML";
